[project]
name = 'USB-Cable-Superposition-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.cable-type-evolution-acceleration-service]
path = 'contracts/cable-type-evolution-acceleration-service.clar'
clarity_version = 3
epoch = '3.2'

[contracts.charging-speed-expectation-reality-gap-maximizer]
path = 'contracts/charging-speed-expectation-reality-gap-maximizer.clar'
clarity_version = 3
epoch = 'latest'

[contracts.connector-orientation-probability-inverter]
path = 'contracts/connector-orientation-probability-inverter.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
